use crate::utils::{file_size_bytes, now_iso8601, sha256_file};
use anyhow::Result;
use rusqlite::Connection;

pub fn register_project_manifest(
    conn: &Connection,
    project_name: &str,
    version: &str,
) -> Result<()> {
    conn.execute(
        "INSERT OR REPLACE INTO project_manifest
         (project_name, project_version, created_at, software_version, db_schema_version, notes)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
        rusqlite::params![
            project_name,
            version,
            now_iso8601(),
            env!("CARGO_PKG_VERSION"),
            "1.0",
            "Auto-generated by gvs ingest-inputs"
        ],
    )?;
    Ok(())
}

pub struct FileEntry<'a> {
    pub role: &'a str,
    pub path: &'a str,
    pub notes: &'a str,
}

pub fn register_input_file(conn: &Connection, entry: &FileEntry) -> Result<String> {
    let hash = sha256_file(entry.path)?;
    let size = file_size_bytes(entry.path)?;
    conn.execute(
        "INSERT OR REPLACE INTO input_files
         (file_role, file_path, sha256_hash, file_size_bytes, imported_at, notes)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
        rusqlite::params![
            entry.role,
            entry.path,
            hash,
            size as i64,
            now_iso8601(),
            entry.notes
        ],
    )?;
    Ok(hash)
}

pub fn get_file_hash(conn: &Connection, role: &str) -> Result<Option<String>> {
    let mut stmt = conn.prepare("SELECT sha256_hash FROM input_files WHERE file_role = ?1")?;
    let mut rows = stmt.query(rusqlite::params![role])?;
    if let Some(row) = rows.next()? {
        Ok(Some(row.get(0)?))
    } else {
        Ok(None)
    }
}

pub fn get_file_id(conn: &Connection, role: &str) -> Result<Option<i64>> {
    let mut stmt = conn.prepare("SELECT file_id FROM input_files WHERE file_role = ?1")?;
    let mut rows = stmt.query(rusqlite::params![role])?;
    if let Some(row) = rows.next()? {
        Ok(Some(row.get(0)?))
    } else {
        Ok(None)
    }
}
